version: '3.8'

services:
  app:
    build: .
    container_name: myapp
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: myapp_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  myapp_network:
    driver: bridge
